services:
  - type: web
    name: social-media-strategist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free 